/**
 * Swagger userstore
 * A sample API that demonstrates Swagger-Express-Middleware features
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { Http, Headers, URLSearchParams }                    from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType }                     from '@angular/http';
import { Observable }                                        from 'rxjs/Observable';
import 'rxjs/add/operator/map';



@Injectable()
export class DefaultApi {

    protected basePath = 'https://localhost:8000';
    public defaultHeaders: Headers = new Headers();
   

    constructor(protected http: Http) {
    }
public getUser(){
return this.http.get("http://localhost:8000/users").map(res=>res.json());
}
}
